/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVien.View;

import NhanVien.Service.ClockService;
import NhanVien.Service.SV_NhanVien;
import NhanVien.ViewModel.VM_BangNV;
import java.sql.SQLException;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class manHinhDangNhap extends javax.swing.JFrame {

    private SV_NhanVien service;

    /**
     * Creates new form manHinhDangNhap
     */
    public manHinhDangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        Clock();
        service = new SV_NhanVien();
    }

    void Clock() {
        ClockService th = new ClockService(btnClock);
        th.start();
        btnClock.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnClock = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        anhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CHÀO MỪNG BẠN ĐẾN VỚI PHẦN MỀM BÁN SÁCH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tài khoản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));
        getContentPane().add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 220, -1));
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 220, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        btnClock.setBackground(new java.awt.Color(204, 255, 255));
        btnClock.setForeground(new java.awt.Color(255, 0, 0));
        btnClock.setText("clock");
        btnClock.setBorder(null);
        btnClock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockActionPerformed(evt);
            }
        });
        getContentPane().add(btnClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Quên mật khẩu ?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, -1));

        anhNen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/hinh-anh-ve-sach-mo-ra_051502949.jpg"))); // NOI18N
        getContentPane().add(anhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 688, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockActionPerformed

    }//GEN-LAST:event_btnClockActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtTaiKhoan.getText().isBlank() || txtMatKhau.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập đủ thông tin");
            return;
        }
        List<VM_BangNV> CV;
        try {
            CV = service.dangNhap(txtTaiKhoan.getText(), txtMatKhau.getText());
            if (CV.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên hoặc mật khẩu sai");
                return;
            } else {
                new Menu().setVisible(true);
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(manHinhDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn quên mật khẩu ???", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (txtTaiKhoan.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Email");
                return;
            }
            List<VM_BangNV> CV;
            try {
                CV = service.HienThitheoEmail(txtTaiKhoan.getText());
                if (CV.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Email này không phải là Email của nhân viên");
                    return;
                }
                final String username = "lamnguyenhoang674@gmail.com";
                final String password = "zpvygpeuplmqigiv";

                Properties prop = new Properties();
                prop.put("mail.smtp.host", "smtp.gmail.com");
                prop.put("mail.smtp.port", "587");
                prop.put("mail.smtp.auth", "true");
                prop.put("mail.smtp.starttls.enable", "true"); //TLS

                Session session = Session.getInstance(prop,
                        new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

                try {

                    Message message = new MimeMessage(session);
                    message.setFrom(new InternetAddress("lamnguyenhoang674@gmail.com"));
                    message.setRecipients(
                            Message.RecipientType.TO,
                            InternetAddress.parse(txtTaiKhoan.getText())
                    );
                    message.setSubject("Phần mềm quản lý bán sách");
                      message.setText("Chào "+ CV.get(0).getTen()
                                    + "\n Chúng tôi nhân được thông tin là bạn bị quên mật khẩu"
                                     + "\n Phần mềm gửi lại bạn thông tin về bạn nhé : "
                             + "\n ID: " +  CV.get(0).getIDNV()
                             + "\n Mã nhân viên: " +  CV.get(0).getMa()
                             + "\n Tên: " +  CV.get(0).getTen()
                             + "\n Chức vụ: " +  CV.get(0).getTenCV()
                             + "\n Email: " +  CV.get(0).getEmail()
                             + "\n Mật khẩu: " +  CV.get(0).getMatKhau()
                            + "\n Bạn kiểm tra lại thông tin của mình và có sai sót gì hãy báo ngay cho chúng tôi nhé : "
                            + "\n Cảm ơn bạn đã sử dụng phầm mềm, chúc bạn có ngày làm việc vui vẻ  "
                            + "\n Thân gửi từ Tô Lâm "
                      );
                    Transport.send(message);
                    JOptionPane.showMessageDialog(this, "Đã gửi về mail của bạn");
                    System.out.println("Done");

                } catch (MessagingException e) {
                    e.printStackTrace();
                }
            } catch (SQLException ex) {
                Logger.getLogger(manHinhDangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manHinhDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhNen;
    private javax.swing.JButton btnClock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
