/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVien.View;

import NhanVien.Service.SV_ChamCong;
import NhanVien.Service.SV_NhanVien;
import NhanVien.ViewModel.VM_BangCC;
import NhanVien.ViewModel.VM_BangNV;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;

/**
 *
 * @author DELL
 */
public class NhanVien extends javax.swing.JFrame {

    private SV_NhanVien serviceNV;
    private SV_ChamCong serviceCC;
    private String mk;
    private String manvvv;

    /**
     * Creates new form NhanVien
     */
    public NhanVien(String mk, String manvvv) throws SQLException {
        initComponents();
        serviceNV = new SV_NhanVien();
        serviceCC = new SV_ChamCong();
        loadTableNV();
        loadTableCC();
        setLocationRelativeTo(null);
        JOptionPane.showMessageDialog(this, "Chào mừng bạn đến với quản lý nhân sự :)))");
        this.mk = mk;
        this.manvvv = manvvv;
        String matKhau = mk;
        String TaiKhoan = manvvv;
        List<VM_BangNV> CV = serviceNV.dangNhap(manvvv, matKhau);
        lb1.setText(CV.get(0).getTen());
    }

    private NhanVien() {

    }

    private void loadTableNV() throws SQLException {
        List<VM_BangNV> CV = serviceNV.HienThi();
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        for (VM_BangNV nv : CV) {
            Object[] row = {nv.getIDNV(), nv.getMa(), nv.getTen(), nv.getGioiTinh(), nv.getNgaySinh(), nv.getEmail(), nv.getSDT(), nv.getDiaChi(), nv.TrangThaiLam(), nv.TrangThaiship(), nv.getTenCV()};
            model.addRow(row);
        }
    }

    private void loadTableCC() throws SQLException {
        List<VM_BangCC> CV = serviceCC.HienThi(String.valueOf(LocalDate.now()));
        DefaultTableModel model = (DefaultTableModel) tblChamCong.getModel();
        model.setRowCount(0);
        for (VM_BangCC nv : CV) {
            Object[] row = {nv.getIdCC(), nv.getIDNV(), nv.getTenNV(), nv.getNgayLam(), nv.getGioIN(), nv.getGioOUT(), nv.TrangThaiCC(), nv.TrangThaiTL()};
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnNV = new javax.swing.JButton();
        rdoTim = new javax.swing.JButton();
        rdoTim1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnChamCong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamCong = new javax.swing.JTable();
        btnChamCong1 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel2 = new javax.swing.JLabel();
        txtIDNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtMaNV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rdoDiLam = new javax.swing.JRadioButton();
        rdoTamNghi = new javax.swing.JRadioButton();
        rdoNghiViec = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rdoCoGiao = new javax.swing.JRadioButton();
        rdoKoGiao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        btnSua = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnSua1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Danh sách nhân viên");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã", "Tên", "Giới tính", "Ngày sinh", "Email", "SĐT", "Địa chỉ", "Trạng thái làm việc", "Trạng thái shipper", "Chức vụ"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        btnNV.setText("Thống kê nhân viên");
        btnNV.setBackground(new java.awt.Color(41, 183, 212));
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });

        rdoTim.setText("Tìm kiếm theo mã");
        rdoTim.setBackground(new java.awt.Color(41, 183, 212));
        rdoTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTimActionPerformed(evt);
            }
        });

        rdoTim1.setText("Quản lý thưởng/phạt,thu/chi nhân viên");
        rdoTim1.setBackground(new java.awt.Color(41, 183, 212));
        rdoTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTim1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoTim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(rdoTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNV)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdoTim)
                    .addComponent(rdoTim1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNV)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel8.setText("Danh sách chấm công");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnChamCong.setText("Tính lương");
        btnChamCong.setBackground(new java.awt.Color(41, 183, 212));
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });

        tblChamCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Nhân viên", "Tên nhân viên", "Ngày", "IN", "OUT", "Trạng thái", "Tính lương"
            }
        ));
        jScrollPane1.setViewportView(tblChamCong);

        btnChamCong1.setText("Chấm công");
        btnChamCong1.setBackground(new java.awt.Color(41, 183, 212));
        btnChamCong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCong1ActionPerformed(evt);
            }
        });

        btnSua2.setText("ĐĂNG XUẤT");
        btnSua2.setBackground(new java.awt.Color(41, 183, 212));
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Quản lý : ");

        lb1.setText("Tô Lâm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217)))
                        .addComponent(btnSua2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChamCong)
                .addGap(41, 41, 41)
                .addComponent(btnChamCong1)
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua2)
                            .addComponent(jLabel16)
                            .addComponent(lb1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamCong)
                    .addComponent(btnChamCong1))
                .addContainerGap())
        );

        jLabel4.setText("Mã");

        jLabel9.setText("Email");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính");

        buttonGroup1.add(rdoNam);
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        jLabel6.setText("Ngày sinh");

        jLabel1.setText("Nhân viên");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setText("ID");

        txtIDNV.setEditable(false);
        txtIDNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNVActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel10.setText("SĐT");

        TxtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaNVActionPerformed(evt);
            }
        });

        jLabel11.setText("Địa chỉ");

        jLabel12.setText("Trạng thái đi làm");

        buttonGroup2.add(rdoDiLam);
        rdoDiLam.setSelected(true);
        rdoDiLam.setText("Đi làm");

        buttonGroup2.add(rdoTamNghi);
        rdoTamNghi.setText("Tạm thời nghỉ");

        buttonGroup2.add(rdoNghiViec);
        rdoNghiViec.setText("Nghỉ việc");
        rdoNghiViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNghiViecActionPerformed(evt);
            }
        });

        jLabel13.setText("Trạng thái shipper");

        buttonGroup3.add(rdoCoGiao);
        rdoCoGiao.setSelected(true);
        rdoCoGiao.setText("Có thể giao hàng");

        buttonGroup3.add(rdoKoGiao);
        rdoKoGiao.setText("Không thể giao hàng");

        jLabel14.setText("Chức vụ");

        btnThem.setText("Thêm");
        btnThem.setBackground(new java.awt.Color(41, 183, 212));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        buttonGroup4.add(rdoQuanLy);
        rdoQuanLy.setSelected(true);
        rdoQuanLy.setText("Quản lý");

        buttonGroup4.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");

        btnSua.setText("Sửa");
        btnSua.setBackground(new java.awt.Color(41, 183, 212));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton4.setText("OUT");
        jButton4.setBackground(new java.awt.Color(41, 183, 212));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("IN");
        jButton6.setBackground(new java.awt.Color(41, 183, 212));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Mật khẩu");

        btnSua1.setText("Reload");
        btnSua1.setBackground(new java.awt.Color(41, 183, 212));
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDNV, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtTen))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdoNam)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdoNu))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoDiLam)
                                .addGap(18, 18, 18)
                                .addComponent(rdoTamNghi)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rdoNghiViec)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(TxtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoCoGiao)
                                    .addComponent(rdoQuanLy))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoNhanVien)
                                    .addComponent(rdoKoGiao))))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rdoDiLam)
                    .addComponent(rdoTamNghi)
                    .addComponent(rdoNghiViec))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rdoCoGiao)
                    .addComponent(rdoKoGiao))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rdoQuanLy)
                    .addComponent(rdoNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnSua1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNVActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void TxtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaNVActionPerformed

    private void rdoNghiViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNghiViecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNghiViecActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int index = tblNhanVien.getSelectedRow();
        if (index >= 0) {
            String idnv = tblNhanVien.getValueAt(index, 0).toString();
            String ma = tblNhanVien.getValueAt(index, 1).toString();
            String ten = tblNhanVien.getValueAt(index, 2).toString();
            String gioitinh = tblNhanVien.getValueAt(index, 3).toString();
            String ngaySinh = tblNhanVien.getValueAt(index, 4).toString();
            String email = tblNhanVien.getValueAt(index, 5).toString();
            String SDT = tblNhanVien.getValueAt(index, 6).toString();
            String diachi = tblNhanVien.getValueAt(index, 7).toString();
            String trangtraiLamViec = tblNhanVien.getValueAt(index, 8).toString();
            String trangtraiGiaoHang = tblNhanVien.getValueAt(index, 9).toString();
            String chucVu = tblNhanVien.getValueAt(index, 10).toString();

            txtIDNV.setText(idnv);
            TxtMaNV.setText(ma);
            txtTen.setText(ten);
            txtDiaChi.setText(diachi);
            datePicker1.setText(ngaySinh);
            txtSDT.setText(SDT);
            txtEmail.setText(email);

            if (gioitinh.equals("Nam")) {
                rdoNam.setSelected(true);
            }
            if (gioitinh.equals("Nữ")) {
                rdoNu.setSelected(true);
            }
            if (trangtraiLamViec.equals("Đang làm")) {
                rdoDiLam.setSelected(true);
            }
            if (trangtraiLamViec.equals("Tạm thời nghỉ")) {
                rdoTamNghi.setSelected(true);
            }
            if (trangtraiLamViec.equals("Nghỉ việc")) {
                rdoNghiViec.setSelected(true);
            }
            if (trangtraiGiaoHang.equals("Có thể giao hàng")) {
                rdoCoGiao.setSelected(true);
            }
            if (trangtraiGiaoHang.equals("Không thể giao hàng")) {
                rdoKoGiao.setSelected(true);
            }
            if (chucVu.equals("Quản lý")) {
                rdoQuanLy.setSelected(true);
            }
            if (chucVu.equals("Nhân viên")) {
                rdoNhanVien.setSelected(true);
            }
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int con = JOptionPane.showConfirmDialog(this, "Bạn muốn sửa dữ liệu nhân viên", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (con == JOptionPane.YES_OPTION) {
            if (tblNhanVien.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Bạn phải chọn nhân viên ở bảng muốn sửa");
                return;
            }

            if (TxtMaNV.getText().isBlank() || txtDiaChi.getText().isBlank() || txtEmail.getText().isBlank() || txtIDNV.getText().isBlank() || txtMatKhau.getText().isBlank() || txtSDT.getText().isBlank() || txtTen.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin");
                return;
            }
            if (patternMatches(txtEmail.getText(), regexPattern) == false) {
                JOptionPane.showMessageDialog(this, "Định dạng Email sai");
                return;
            }
            if (!datePicker1.getDate().isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Ngày sinh phải nhỏ hơn ngày hiện tại");
                return;
            }
            if (patternMatches(txtSDT.getText(), regSDT) == false) {
                JOptionPane.showMessageDialog(this, "Định dạng SĐT sai");
                return;
            } else {
                VM_BangNV nv = new VM_BangNV();
                String manv = TxtMaNV.getText();
                String tennv = txtTen.getText();
                String diaChi = txtDiaChi.getText();

                String email = txtEmail.getText();

                String SDT = txtSDT.getText();
                String ngaySinh = datePicker1.getText();
                String matKhau = txtMatKhau.getText();
                nv.setDiaChi(diaChi);
                nv.setEmail(email);

                nv.setMa(manv);
                nv.setMatKhau(matKhau);
                nv.setNgaySinh(ngaySinh);
                nv.setSDT(SDT);
                nv.setTen(tennv);

                if (rdoNam.isSelected()) {
                    nv.setGioiTinh("Nam");
                }
                if (rdoNu.isSelected()) {
                    nv.setGioiTinh("Nữ");
                }
                if (rdoDiLam.isSelected()) {
                    nv.setTrangThaiDiLam(1);
                }
                if (rdoTamNghi.isSelected()) {
                    nv.setTrangThaiDiLam(2);
                }
                if (rdoNghiViec.isSelected()) {
                    nv.setTrangThaiDiLam(3);
                }
                if (rdoCoGiao.isSelected()) {
                    nv.setTrangTháihipper(1);
                }
                if (rdoKoGiao.isSelected()) {
                    nv.setTrangTháihipper(2);
                }
                if (rdoQuanLy.isSelected()) {
                    nv.setTenCV("1");
                }
                if (rdoNhanVien.isSelected()) {
                    nv.setTenCV("2");
                }

                try {
                    List<VM_BangNV> CV = serviceNV.HienThitheoMa(manv);
                    VM_BangNV n = serviceNV.HienThitheoMa(manv).get(0);

                    if (CV.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy đối tượng");
                        return;
                    }
                    List<VM_BangNV> C = serviceNV.HienThitheoEmail(txtEmail.getText());

                    if (n.getTrangThaiDiLam() == 3) {
                        JOptionPane.showMessageDialog(this, "Nhân viên đã nghỉ nên không thể sửa");
                        return;
                    }

                    if (C.isEmpty()) {

                        try {
                            serviceNV.update(manv, nv);
                            loadTableNV();
                            JOptionPane.showMessageDialog(this, "Sửa thành công");
                            txtDiaChi.setText("");

                            TxtMaNV.setText("");
                            txtEmail.setText("");
                            txtIDNV.setText("");
                            txtMatKhau.setText("");
                            txtSDT.setText("");
                            txtTen.setText("");

                            txtIDNV.setText("");
                            rdoCoGiao.setSelected(true);
                            rdoNam.setSelected(true);
                            rdoQuanLy.setSelected(true);
                            rdoDiLam.setSelected(true);
                        } catch (SQLException ex) {
                            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_btnSuaActionPerformed
    public static boolean patternMatches(String emailAddress, String regexPattern) {
        return Pattern.compile(regexPattern)
                .matcher(emailAddress)
                .matches();
    }
    String regexPattern = "^[a-zA-Z][\\w-]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,})$";
    String regSDT = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        int con = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm nhân viên", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (con == JOptionPane.YES_OPTION) {

            if (TxtMaNV.getText().isBlank() || txtDiaChi.getText().isBlank() || txtEmail.getText().isBlank() || txtMatKhau.getText().isBlank() || txtSDT.getText().isBlank() || txtTen.getText().isBlank() || datePicker1.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin");
                return;
            }
            if (patternMatches(txtEmail.getText(), regexPattern) == false) {
                JOptionPane.showMessageDialog(this, "Định dạng Email sai");
                return;
            }
            if (!datePicker1.getDate().isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Ngày sinh phải nhỏ hơn ngày hiện tại");
                return;
            }
            if (patternMatches(txtSDT.getText(), regSDT) == false) {
                JOptionPane.showMessageDialog(this, "Định dạng SĐT sai");
                return;
            } else {
                VM_BangNV nv = new VM_BangNV();
                String manv = TxtMaNV.getText();
                String tennv = txtTen.getText();
                String diaChi = txtDiaChi.getText();

                String email = txtEmail.getText();

                String SDT = txtSDT.getText();
                String ngaySinh = datePicker1.getText();
                String matKhau = txtMatKhau.getText();
                nv.setDiaChi(diaChi);
                nv.setEmail(email);

                nv.setMa(manv);
                nv.setMatKhau(matKhau);
                nv.setNgaySinh(ngaySinh);
                nv.setSDT(SDT);
                nv.setTen(tennv);

                if (rdoNam.isSelected()) {
                    nv.setGioiTinh("Nam");
                }
                if (rdoNu.isSelected()) {
                    nv.setGioiTinh("Nữ");
                }
                if (rdoDiLam.isSelected()) {
                    nv.setTrangThaiDiLam(1);
                }
                if (rdoTamNghi.isSelected()) {
                    nv.setTrangThaiDiLam(2);
                }
                if (rdoNghiViec.isSelected()) {
                    nv.setTrangThaiDiLam(3);
                }
                if (rdoCoGiao.isSelected()) {
                    nv.setTrangTháihipper(1);
                }
                if (rdoKoGiao.isSelected()) {
                    nv.setTrangTháihipper(2);
                }
                if (rdoQuanLy.isSelected()) {
                    nv.setTenCV("1");
                }
                if (rdoNhanVien.isSelected()) {
                    nv.setTenCV("2");
                }
                String id = txtIDNV.getText();

                try {
                    List<VM_BangNV> CV = serviceNV.HienThitheoMa(manv);

                    if (!CV.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Trùng mã");
                        return;
                    }
                    List<VM_BangNV> C = serviceNV.HienThitheoEmail(txtEmail.getText());
                    if (!C.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Trùng Email");
                        return;
                    } else {
                        try {
                            serviceNV.insert(nv);
                            loadTableNV();
                            JOptionPane.showMessageDialog(this, "Thêm thành công");
                            txtDiaChi.setText("");

                            TxtMaNV.setText("");
                            txtEmail.setText("");
                            txtIDNV.setText("");
                            txtMatKhau.setText("");
                            txtSDT.setText("");
                            txtTen.setText("");

                            txtIDNV.setText("");
                            rdoCoGiao.setSelected(true);
                            rdoNam.setSelected(true);
                            rdoQuanLy.setSelected(true);
                            rdoDiLam.setSelected(true);
                        } catch (SQLException ex) {
                            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void rdoTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTimActionPerformed
        if (TxtMaNV.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập mã nhân viên trước");
            return;
        }
        try {
            // TODO add your handling code here:
            List<VM_BangNV> CV = serviceNV.HienThitheoMa(TxtMaNV.getText());
            if (CV.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
            } else {
                DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
                model.setRowCount(0);
                for (VM_BangNV nv : CV) {
                    Object[] row = {nv.getIDNV(), nv.getMa(), nv.getTen(), nv.getGioiTinh(), nv.getNgaySinh(), nv.getEmail(), nv.getSDT(), nv.getDiaChi(), nv.TrangThaiLam(), nv.TrangThaiship(), nv.getTenCV()};
                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_rdoTimActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        TxtMaNV.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtIDNV.setText("");
        txtMatKhau.setText("");
        txtSDT.setText("");
        txtTen.setText("");
        datePicker1.setText("");
        rdoCoGiao.setSelected(true);
        rdoNam.setSelected(true);
        rdoDiLam.setSelected(true);
        rdoQuanLy.setSelected(true);
        try {
            loadTableNV();
            loadTableCC();
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        int con = JOptionPane.showConfirmDialog(this, "Bạn muốn IN ca cho nhân viên có mã " + TxtMaNV.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
        if (con == JOptionPane.YES_OPTION) {
            if (txtIDNV.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải tìm ID nhân viên trước");
                return;
            } else {
                try {
                    List<VM_BangCC> CCC = serviceCC.CheckTinhTrangDiLam(txtIDNV.getText());
                    if (CCC.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Nhân viên có thể đang tạm thời nghỉ hoặc là đã nghỉ việc");
                        return;
                    } else {
                        try {

                            List<VM_BangCC> CV = serviceCC.CheckIN(String.valueOf(LocalDate.now()), txtIDNV.getText());
                            if (CV.isEmpty()) {
                                VM_BangCC cc = new VM_BangCC();
                                cc.setIDNV(txtIDNV.getText());
                                cc.setNgayLam(String.valueOf(LocalDate.now()));

                                cc.setTrangThai(1);
                                serviceCC.insert(cc);
                                loadTableCC();
                                JOptionPane.showMessageDialog(this, "IN thành công");

                            } else {
                                JOptionPane.showMessageDialog(this, "Nhân viên đang IN");
                                return;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int con = JOptionPane.showConfirmDialog(this, "Bạn muốn OUT ca cho nhân viên", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (con == JOptionPane.YES_OPTION) {
            if (txtIDNV.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải tìm ID nhân viên trước");
                return;
            } else {
                try {

                    List<VM_BangCC> CV = serviceCC.CheckOUT(String.valueOf(LocalDate.now()), txtIDNV.getText());
                    List<VM_BangCC> CC = serviceCC.CheckIN(String.valueOf(LocalDate.now()), txtIDNV.getText());
                    if (CC.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Nhân viên chưa IN hoặc đã OUT");
                        return;
                    } else {
                        serviceCC.update(txtIDNV.getText(), String.valueOf(LocalDate.now()));
                        loadTableCC();
                        JOptionPane.showMessageDialog(this, "OUT thành công");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdoTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTim1ActionPerformed
        try {
            // TODO add your handling code here:

            new CTThuong().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rdoTim1ActionPerformed

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        try {
            // TODO add your handling code here:
            new tinhLuong().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChamCongActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        try {
            // TODO add your handling code here:
            new ThongKeNV().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNVActionPerformed

    private void btnChamCong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCong1ActionPerformed
        // TODO add your handling code here:
        new ChamCong().setVisible(true);
    }//GEN-LAST:event_btnChamCong1ActionPerformed

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
        int con = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (con == JOptionPane.YES_OPTION) {
            new dangNhapNV().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnSua2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMaNV;
    private javax.swing.JButton btnChamCong;
    private javax.swing.JButton btnChamCong1;
    private javax.swing.JButton btnNV;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JRadioButton rdoCoGiao;
    private javax.swing.JRadioButton rdoDiLam;
    private javax.swing.JRadioButton rdoKoGiao;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiViec;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JRadioButton rdoTamNghi;
    private javax.swing.JButton rdoTim;
    private javax.swing.JButton rdoTim1;
    private javax.swing.JTable tblChamCong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
