/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duan1.View.QLHD;

import com.mycompany.duan1.Entity.CTSach;
import com.mycompany.duan1.Entity.CartItem;
import com.mycompany.duan1.Entity.KhachHang;
import com.mycompany.duan1.Entity.ThongTinChiTiet;
import com.mycompany.duan1.Service.CTSachService;
import com.mycompany.duan1.Service.Impl.CTSachServiceImpl;
import com.mycompany.duan1.Service.Impl.KhachHangServiceImpl;
import com.mycompany.duan1.Service.KhachHangService;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.text.Collator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class AddBookToHDJframe extends javax.swing.JFrame {

    private final createHDJPanel createHDJPanel;
    private final CTSachService ctsachservice = new CTSachServiceImpl();
    List<CTSach> listCTSach = ctsachservice.findAll();
    DefaultTableModel dtm;

    public AddBookToHDJframe(createHDJPanel currentcreatehDJPanel) {
        this.createHDJPanel = currentcreatehDJPanel;
        initComponents();
        setLocationRelativeTo(null);

        dtm = (DefaultTableModel) tblDanhSachBook.getModel();
        //

        //
        loadDataToTable();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachBook = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Search/Filter:");

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        tblDanhSachBook.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblDanhSachBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Sách", "Nhà Xuất bản", "NXB", "Chất Liệu", "Ngôn ngữ", "Số lượng", "Giá bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachBook);
        if (tblDanhSachBook.getColumnModel().getColumnCount() > 0) {
            tblDanhSachBook.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblDanhSachBook.getColumnModel().getColumn(1).setPreferredWidth(155);
            tblDanhSachBook.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblDanhSachBook.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblDanhSachBook.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblDanhSachBook.getColumnModel().getColumn(5).setPreferredWidth(30);
            tblDanhSachBook.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblDanhSachBook.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed

    }//GEN-LAST:event_txtFilterActionPerformed

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        String query = txtFilter.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtFilterKeyReleased

    private void tblDanhSachBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachBookMouseClicked
        int index = tblDanhSachBook.getSelectedRow();
        Long idCTSach = (Long) tblDanhSachBook.getValueAt(index, 0);
        String tenSach = (String) tblDanhSachBook.getValueAt(index, 1);
        BigDecimal donGia = (BigDecimal) tblDanhSachBook.getValueAt(index, 7);
        CartItem cartitem = new CartItem(idCTSach, tenSach, 1, donGia);
        boolean exist = false;
        for (CartItem item : createHDJPanel.danhsachchon) {
            if (idCTSach.equals(item.getId())) {
                item.setSoLuong(item.getSoLuong() + 1);
                createHDJPanel.loadToTableSPMua(createHDJPanel.danhsachchon);
                exist = true;
                break;
            }
        }
        if (!exist) {
            createHDJPanel.danhsachchon.add(cartitem);
            createHDJPanel.loadToTableSPMua(createHDJPanel.danhsachchon);

        }
        createHDJPanel.logicTinhTongTienSauKhiTangOrGiamOrXoaSPTrongBang();

        //Set Số luong sách trong db sau khi them sách vào danh sách chọn
        CTSach cts = ctsachservice.findById(idCTSach);
        int soluongsachhientaitrongdb = cts.getSoLuong();
        int soLuongSachConLaiTrongDBSauKhiAnThem = soluongsachhientaitrongdb - 1;
        ctsachservice.updateSoLuongCTSach(idCTSach, soLuongSachConLaiTrongDBSauKhiAnThem);
        this.dispose();
    }//GEN-LAST:event_tblDanhSachBookMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDanhSachBook;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {
        dtm.setRowCount(0);
        for (CTSach ctsach : listCTSach) {
            dtm.addRow(new Object[]{ctsach.getIdCTSach(), ctsach.getSach().getTen(), ctsach.getNhaxuatban().getTen(), ctsach.getNamxuatban().getNam(),
                ctsach.getChatlieu().getTen(), ctsach.getNgonngu().getTen(), ctsach.getSoLuong(), ctsach.getGiaBan()});
        }
    }

//    TableRowSorter cung cấp các phương thức và thuộc tính để thực hiện các hoạt động sắp xếp và lọc dữ liệu, bao gồm:
//
//setSortable(int column, boolean sortable): Đặt tính khả năng sắp xếp của cột được chỉ định.
//setRowFilter(RowFilter<? super M, ? super I> filter): Đặt bộ lọc hàng để áp dụng cho bảng.
//toggleSortOrder(int column): Chuyển đổi trạng thái sắp xếp của cột được chỉ định (tăng dần hoặc giảm dần).
//setSortKeys(List<? extends SortKey> sortKeys): Đặt danh sách các khóa sắp xếp để xác định thứ tự sắp xếp của các cột.
//getFilteredRowCount(): Trả về số lượng hàng đang được hiển thị sau khi áp dụng bộ lọc.
//TableRowSorter có thể được gắn kết với một JTable bằng cách sử dụng 
//    phương thức setRowSorter(TableRowSorter<? extends TableModel> sorter) của JTable. 
//    Khi TableRowSorter được gắn kết với JTable, người dùng có thể sắp xếp và lọc 
//    dữ liệu bằng cách nhấp vào tiêu đề của các cột hoặc sử dụng các công cụ sắp xếp và lọc được cung cấp.
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tblDanhSachBook.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + escapeSpecialCharacters(query), getColumnIndices()));
    }

    private String escapeSpecialCharacters(String text) {
        // Escape special regex characters
        return text.replaceAll("([\\\\^$*+?.\\(\\)\\|\\[\\]\\{\\}])", "\\\\$1");
    }

    private int[] getColumnIndices() {
        // Return an array of column indices to apply the filter
        // You can customize this method based on your table's structure
        int numColumns = dtm.getColumnCount();
        int[] indices = new int[numColumns];
        for (int i = 0; i < numColumns; i++) {
            indices[i] = i;
        }
        return indices;
    }

    private Collator getCollator() {
        // Create a Collator with Locale specific rules
        // This example uses Vietnamese Locale
        Locale locale = new Locale("vi", "VN");
        return Collator.getInstance(locale);
    }

}
