/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duan1.View.QLHD;

import com.mycompany.duan1.Entity.LichSuGiaoHang;
import com.mycompany.duan1.Entity.NhanVien;
import com.mycompany.duan1.Repository.Impl.LichSuGiaoHangRepoImpl;
import com.mycompany.duan1.Repository.LichSuGiaoHangRepo;
import com.mycompany.duan1.Service.Impl.NhanVienServiceImpl;
import com.mycompany.duan1.Service.NhanVienService;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChiTietGiaoHangJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietGiaoHang
     */
    private PGHChiTietJrame pGHChiTietJrame;
    private NhanVienService nvService = new NhanVienServiceImpl();
    private LichSuGiaoHangRepo lichSuGiaoHangRepo = new LichSuGiaoHangRepoImpl();
    DefaultComboBoxModel dccb;
    DefaultTableModel dtm;

    SimpleDateFormat sdf = new SimpleDateFormat();

    public ChiTietGiaoHangJFrame(PGHChiTietJrame pGHChiTietJrame) {
        this.pGHChiTietJrame = pGHChiTietJrame;
        initComponents();
        setLocationRelativeTo(null);
        loadView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinGH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        txtMaPGH = new javax.swing.JTextField();
        txtNgayGiaoHang = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        ccbTrangThai = new javax.swing.JComboBox<>();
        cbbNVGH = new javax.swing.JComboBox<>();
        txtHoTenNhanVien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblThongTinGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID PGH", "ID NV", "Nhân viên giao hàng", "Ngày Giao Hàng", "Trang Thái", "Ghi chú"
            }
        ));
        tblThongTinGH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinGHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinGH);

        jLabel1.setText("Mã NVGH :");

        jLabel2.setText("Mã PGH:");

        jLabel3.setText("Ngày giao hàng:");

        jLabel4.setText("Trạng Thái:");

        jLabel5.setText("Ghi chú:");

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        txtMaPGH.setEditable(false);
        txtMaPGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPGHActionPerformed(evt);
            }
        });

        txtNgayGiaoHang.setEditable(false);
        txtNgayGiaoHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnUpdate.setText("Update");

        ccbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huỷ", "Đang giao hàng", "Hoàn thành" }));
        ccbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbTrangThaiActionPerformed(evt);
            }
        });

        cbbNVGH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Nhân viên" }));
        cbbNVGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNVGHActionPerformed(evt);
            }
        });

        txtHoTenNhanVien.setEditable(false);
        txtHoTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPGH, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnADD)
                                .addGap(176, 176, 176)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbbNVGH, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHoTenNhanVien))
                                .addComponent(txtNgayGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ccbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPGH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNVGH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ccbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(btnUpdate))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed

    }//GEN-LAST:event_btnADDActionPerformed

    private void ccbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccbTrangThaiActionPerformed

    private void cbbNVGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNVGHActionPerformed
//        Long idNV = (Long) dccb.getSelectedItem();
//        Optional<NhanVien> nv = nvService.findNVById(idNV);
//        txtHoTenNhanVien.setText(nv.get().getTen());

    }//GEN-LAST:event_cbbNVGHActionPerformed

    private void txtMaPGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPGHActionPerformed
//        add();
    }//GEN-LAST:event_txtMaPGHActionPerformed

    private void txtHoTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenNhanVienActionPerformed

    private void tblThongTinGHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinGHMouseClicked

    }//GEN-LAST:event_tblThongTinGHMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChiTietGiaoHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChiTietGiaoHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChiTietGiaoHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChiTietGiaoHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChiTietGiaoHangJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbNVGH;
    private javax.swing.JComboBox<String> ccbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongTinGH;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTenNhanVien;
    private javax.swing.JTextField txtMaPGH;
    private javax.swing.JTextField txtNgayGiaoHang;
    // End of variables declaration//GEN-END:variables

    private void loadView() {
        txtMaPGH.setText((pGHChiTietJrame.txtMAPGH.getText()));
        Optional<List<NhanVien>> otp = nvService.findAll();
        dccb = (DefaultComboBoxModel) cbbNVGH.getModel();
        List<NhanVien> listNV;
        if (otp.isPresent()) {
            if (!otp.get().isEmpty()) {
                listNV = otp.get();
                for (NhanVien item : listNV) {
                    if (item.getTrangThaiShipper() == 1) {
                        dccb.addElement(item.getId());
                    }
                }
            }
        }
        Date ngayGiaoHang = new Date();
        txtNgayGiaoHang.setText(sdf.format(ngayGiaoHang));

        //Set View Table
        dtm = (DefaultTableModel) tblThongTinGH.getModel();
        dtm.setRowCount(0);

        Optional<List<LichSuGiaoHang>> otpLSGH = lichSuGiaoHangRepo.findAll();
        if (otpLSGH.isPresent()) {
            if (!otpLSGH.get().isEmpty()) {
                for (LichSuGiaoHang item : otpLSGH.get()) {
                    dtm.addRow(new Object[]{item.getPghLSGH().getId(),item.getNhanvien().getId(), item.getNhanvien().getTen(), item.getNgayGiaoHang(), item.getTrangThai(), item.getGhiChu()});
                }
            }
        }
    }

//    private void add() {
//        int rowIndex = tblThongTinGH.getSelectedRow();
//        Long idPGH = (Long) tblThongTinGH.getValueAt(rowIndex, 0);
//        Long idNV = (Long) tblThongTinGH.getValueAt(rowIndex, 0);
//    }
}
