/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duan1.View.QLHD;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.mycompany.duan1.Entity.ThongTinTK;
import com.mycompany.duan1.Service.HoaDonService;
import com.mycompany.duan1.Service.Impl.HoaDonServiceImpl;
import com.mycompany.duan1.View.QRCode;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChonHinhThucThanhToanJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChonHinhThucThanhToanJFrame
     */
    DetailHDJFrame detailHDJFrame;
    private HoaDonService hoaDonService = new HoaDonServiceImpl();

    public ChonHinhThucThanhToanJFrame(DetailHDJFrame detailHDJFrame) {
        this.detailHDJFrame = detailHDJFrame;
        initComponents();
        setLocationRelativeTo(null);
//        setView
        jpnChucNang.removeAll();
        jpnChucNang.setLayout(new BorderLayout());
        jpnChucNang.add(jpnTienMat);
        jpnChucNang.validate();
        jpnChucNang.repaint();

        txtTongTienHĐ.setText(detailHDJFrame.txtTotal.getText());

        //Set thông tin tk
        loadDataToTableTTTK();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHinhThucThanhToan = new javax.swing.ButtonGroup();
        jpnTienMat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTienThua = new javax.swing.JTextField();
        jpnChuyenKhoan = new javax.swing.JPanel();
        btnTaoQRCode = new javax.swing.JButton();
        btnThanhThoan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinTK = new javax.swing.JTable();
        jpnRoot = new javax.swing.JPanel();
        jpnChucNang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdoTienMat = new javax.swing.JRadioButton();
        rdoChuyenKhoann = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtTongTienHĐ = new javax.swing.JTextField();

        jLabel3.setText("Tiền khách đưa :");

        jLabel4.setText("Tiền thừa :");

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtTienThua.setEditable(false);
        txtTienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTienMatLayout = new javax.swing.GroupLayout(jpnTienMat);
        jpnTienMat.setLayout(jpnTienMatLayout);
        jpnTienMatLayout.setHorizontalGroup(
            jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTienMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienKhachDua)
                    .addComponent(txtTienThua)
                    .addGroup(jpnTienMatLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnThanhToan)
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnTienMatLayout.setVerticalGroup(
            jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTienMatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jpnTienMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThanhToan)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnTaoQRCode.setText("Tạo QR");
        btnTaoQRCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoQRCodeActionPerformed(evt);
            }
        });

        btnThanhThoan.setText("Thanh Toán");
        btnThanhThoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhThoanActionPerformed(evt);
            }
        });

        tblThongTinTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Chủ thẻ", "Ngân hàng", "Số tài khoản"
            }
        ));
        tblThongTinTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinTK);

        javax.swing.GroupLayout jpnChuyenKhoanLayout = new javax.swing.GroupLayout(jpnChuyenKhoan);
        jpnChuyenKhoan.setLayout(jpnChuyenKhoanLayout);
        jpnChuyenKhoanLayout.setHorizontalGroup(
            jpnChuyenKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChuyenKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnChuyenKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnChuyenKhoanLayout.createSequentialGroup()
                        .addComponent(btnThanhThoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoQRCode))
                    .addGroup(jpnChuyenKhoanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnChuyenKhoanLayout.setVerticalGroup(
            jpnChuyenKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChuyenKhoanLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnChuyenKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhThoan)
                    .addComponent(btnTaoQRCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jpnChucNangLayout = new javax.swing.GroupLayout(jpnChucNang);
        jpnChucNang.setLayout(jpnChucNangLayout);
        jpnChucNangLayout.setHorizontalGroup(
            jpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnChucNangLayout.setVerticalGroup(
            jpnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Chọn hình thức thanh toán :");

        buttonGroupHinhThucThanhToan.add(rdoTienMat);
        rdoTienMat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoTienMat.setSelected(true);
        rdoTienMat.setText("Tiền mặt");
        rdoTienMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTienMatActionPerformed(evt);
            }
        });

        buttonGroupHinhThucThanhToan.add(rdoChuyenKhoann);
        rdoChuyenKhoann.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoChuyenKhoann.setText("Chuyển khoản");
        rdoChuyenKhoann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChuyenKhoannActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tổng tiền Hoá Đơn  :");

        txtTongTienHĐ.setEditable(false);
        txtTongTienHĐ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTongTienHĐ.setForeground(new java.awt.Color(255, 51, 51));
        txtTongTienHĐ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongTienHĐ.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTongTienHĐ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienHĐActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTienHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoTienMat)
                        .addGap(18, 18, 18)
                        .addComponent(rdoChuyenKhoann)))
                .addGap(20, 20, 20))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTongTienHĐ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdoTienMat)
                    .addComponent(rdoChuyenKhoann))
                .addGap(18, 18, 18)
                .addComponent(jpnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    private void txtTienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienThuaActionPerformed

    private void rdoTienMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTienMatActionPerformed
        jpnChucNang.removeAll();
        jpnChucNang.setLayout(new BorderLayout());
        jpnChucNang.add(jpnTienMat);
        jpnChucNang.validate();
        jpnChucNang.repaint();
    }//GEN-LAST:event_rdoTienMatActionPerformed

    private void rdoChuyenKhoannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChuyenKhoannActionPerformed
        jpnChucNang.removeAll();
        jpnChucNang.setLayout(new BorderLayout());
        jpnChucNang.add(jpnChuyenKhoan);
        jpnChucNang.validate();
        jpnChucNang.repaint();
    }//GEN-LAST:event_rdoChuyenKhoannActionPerformed

    private void txtTongTienHĐActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienHĐActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienHĐActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        if (!txtTienKhachDua.getText().equals("")) {
            Double tienKhachDua = Double.valueOf(txtTienKhachDua.getText());
            Double tongtienhd = Double.valueOf(txtTongTienHĐ.getText());
            Double tienthua = tienKhachDua - tongtienhd;
            txtTienThua.setText(String.valueOf(tienthua));
        }

    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnThanhThoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhThoanActionPerformed
        Long idHD = Long.valueOf(detailHDJFrame.txtIdHD.getText());
        System.out.println("Mã HĐ là:" + idHD);
        hoaDonService.updateTrangThaiHD(idHD, Long.valueOf("3"));
        hoaDonService.updateHinhThucThanhToan(idHD, Long.valueOf("4"));

        detailHDJFrame.jpnChuongTrinhHoaDon.removeAll();
        detailHDJFrame.jpnChuongTrinhHoaDon.setLayout(new BorderLayout());
        detailHDJFrame.jpnChuongTrinhHoaDon.add(detailHDJFrame.jpnDaThanhToan);
        detailHDJFrame.jpnChuongTrinhHoaDon.revalidate();
        detailHDJFrame.jpnChuongTrinhHoaDon.repaint();
        detailHDJFrame.txtKM.setText("Chuyển khoản");
        detailHDJFrame.txtTrangThai.setText("Đã thanh toán");
        this.dispose();
    }//GEN-LAST:event_btnThanhThoanActionPerformed

    private void btnTaoQRCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoQRCodeActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblThongTinTK.getModel();
        int indexRow = tblThongTinTK.getSelectedRow();
        if (indexRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn Tài khoản");
            return;
        }
        String chuThe = (String) tblThongTinTK.getValueAt(indexRow, 0);
        String STK = (String) tblThongTinTK.getValueAt(indexRow, 1);
        String nganHang = (String) tblThongTinTK.getValueAt(indexRow, 2);
        double giaTriHD = Double.parseDouble(txtTongTienHĐ.getText());
        new QRCode(chuThe, STK, nganHang, giaTriHD).setVisible(true);


    }//GEN-LAST:event_btnTaoQRCodeActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        Long idHD = Long.valueOf(detailHDJFrame.txtIdHD.getText());
        System.out.println("Mã HĐ là:" + idHD);
        hoaDonService.updateTrangThaiHD(idHD, Long.valueOf("3"));
        hoaDonService.updateHinhThucThanhToan(idHD, Long.valueOf("2"));

        detailHDJFrame.jpnChuongTrinhHoaDon.removeAll();
        detailHDJFrame.jpnChuongTrinhHoaDon.setLayout(new BorderLayout());
        detailHDJFrame.jpnChuongTrinhHoaDon.add(detailHDJFrame.jpnDaThanhToan);
        detailHDJFrame.jpnChuongTrinhHoaDon.revalidate();
        detailHDJFrame.jpnChuongTrinhHoaDon.repaint();
        detailHDJFrame.txtKM.setText("Tiền mặt");
        detailHDJFrame.txtTrangThai.setText("Đã thanh toán");
        this.dispose();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblThongTinTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinTKMouseClicked

    }//GEN-LAST:event_tblThongTinTKMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChonHinhThucThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChonHinhThucThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChonHinhThucThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChonHinhThucThanhToanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChonHinhThucThanhToanJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoQRCode;
    private javax.swing.JButton btnThanhThoan;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.ButtonGroup buttonGroupHinhThucThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnChucNang;
    private javax.swing.JPanel jpnChuyenKhoan;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTienMat;
    private javax.swing.JRadioButton rdoChuyenKhoann;
    private javax.swing.JRadioButton rdoTienMat;
    private javax.swing.JTable tblThongTinTK;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTienHĐ;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTableTTTK() {
        List<ThongTinTK> listTk = new ArrayList();
        listTk.add(new ThongTinTK("Tran Tuan Linh", "Vietcombank", "001100"));
        listTk.add(new ThongTinTK("Tran Tuan Linh", "Viettinbank", "001100"));
        DefaultTableModel dtm = (DefaultTableModel) tblThongTinTK.getModel();
        dtm.setRowCount(0);
        for (ThongTinTK thongTinTK : listTk) {
            dtm.addRow(new Object[]{thongTinTK.getChuThe(), thongTinTK.getNganHang(), thongTinTK.getNganHang()});
        }
    }

}
