/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DotKhuyenMai.view;

import NhanVien.View.dangNhapHD;
import DotKhuyenMai.model.GioHangModel;
import DotKhuyenMai.model.Hienthigannhat;
import DotKhuyenMai.model.HoaDonChiTietModel;
import DotKhuyenMai.model.HoaDonMode;
import DotKhuyenMai.model.KhachHangModel;
import DotKhuyenMai.model.SanPhamModel;
import DotKhuyenMai.model.giamGiamodel;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DotKhuyenMai.service.KhachHangService;

/**
 *
 * @author DELL
 */
public class HoaDon extends javax.swing.JFrame {

    private KhachHangService service = new KhachHangService();
    DefaultTableModel model = new DefaultTableModel();
    List<KhachHangModel> list = new ArrayList<>();
    private String mk;
    private String manvvv;

    /**
     * Creates new form HoaDon
     */
    public HoaDon(String mk, String manvvv) throws SQLException {
        initComponents();
        this.mk = mk;
        this.manvvv = manvvv;
        String matKhau = mk;
        String TaiKhoan = manvvv;
        List<KhachHangModel> CV = service.dangNhap(manvvv, matKhau);
        lb1.setText(CV.get(0).getMaKH());
        lb2.setText(CV.get(0).getTenKH());
        lb3.setText(CV.get(0).getGioiTinh());
        loadTableGG();
    }

    private HoaDon() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblKH = new javax.swing.JTable();
        kkk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSP = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaKH_HD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdo_tienMat = new javax.swing.JRadioButton();
        rdo_quet = new javax.swing.JRadioButton();
        rdo_chuyen = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoadon = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMHD_GH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSP_GH = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSoLuong_GH = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtMaHD_HD = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtGG_GH = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblGiamGia = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtKhachDua = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        txtTinhTong = new javax.swing.JTextField();
        txtGuiLai = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        jButton15 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtGiamGIa = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        jLabel24.setText("Mã nhân viên");

        jLabel25.setText("-------");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Khách hàng : ");

        jLabel2.setText("Số điện thoại");

        TblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID khách hàng", "Tên", "Cấp bậc", "Giới tính", "Số điện thoại"
            }
        ));
        TblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblKH);

        kkk.setBackground(new java.awt.Color(41, 183, 212));
        kkk.setText("Tìm kiếm");
        kkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sản phẩm");

        jLabel4.setText("ID sản phẩm");

        jButton2.setBackground(new java.awt.Color(41, 183, 212));
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số lượng", "Giá"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSPMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblSP);
        if (tblSP.getColumnModel().getColumnCount() > 0) {
            tblSP.getColumnModel().getColumn(0).setResizable(false);
            tblSP.getColumnModel().getColumn(1).setResizable(false);
            tblSP.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tạo hóa đơn");

        jLabel6.setText("ID Khách hàng");

        jLabel7.setText("ID  nhân viên");

        txtMaKH_HD.setEditable(false);

        jLabel9.setText("Thanh Toán");

        buttonGroup1.add(rdo_tienMat);
        rdo_tienMat.setSelected(true);
        rdo_tienMat.setText("Tiền mặt");

        buttonGroup1.add(rdo_quet);
        rdo_quet.setText("Quẹt thẻ");

        buttonGroup1.add(rdo_chuyen);
        rdo_chuyen.setText("Chuyển khoản");

        jButton1.setBackground(new java.awt.Color(41, 183, 212));
        jButton1.setText("Thêm hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(41, 183, 212));
        jButton3.setText("Hủy hóa đơn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID hóa đơn", "Tên khách hàng", "Thanh toán", "Ngày tạo", "Giảm giá", "Trạng thái"
            }
        ));
        tblHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoadonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoadon);

        jButton4.setBackground(new java.awt.Color(41, 183, 212));
        jButton4.setText("Tìm kiếm hóa đơn theo ID khách hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Giỏ hàng");

        jLabel14.setText("ID Hóa Đơn");

        txtMHD_GH.setEditable(false);

        jLabel15.setText("ID sản phẩm");

        txtSP_GH.setEditable(false);

        jLabel16.setText("Số lượng");

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Hóa đơn", "ID Sách", "Tên Sách", "Số lượng", "Giá bán"
            }
        ));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblGioHang);

        jButton5.setBackground(new java.awt.Color(41, 183, 212));
        jButton5.setText("Danh sách hóa đơn");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Hóa đơn");

        jButton6.setBackground(new java.awt.Color(41, 183, 212));
        jButton6.setText("Tìm kiếm hóa đơn theo ID hóa đơn");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(41, 183, 212));
        jButton7.setText("Thêm vài giỏ hàng");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(41, 183, 212));
        jButton8.setText("Xóa sản phẩm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(41, 183, 212));
        jButton9.setText("Hiển thị sản phẩm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel18.setText("ID giảm giá");

        txtGG_GH.setEditable(false);

        tblGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã giảm giá", "Tên", "Mức", "Ngày BD", "Ngày KT"
            }
        ));
        tblGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblGiamGia);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Chương trình giảm giá có thể áp dụng");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtTrangThai.setEditable(false);

        jLabel26.setText("Tổng tiền");

        jLabel28.setText("Số tiền khách đưa");

        jLabel30.setText("Gửi lại");

        txtKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachDuaActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(41, 183, 212));
        jButton11.setText("Tính tổng");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(41, 183, 212));
        jButton12.setText("Thanh toán");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        txtTinhTong.setEditable(false);

        txtGuiLai.setEditable(false);

        jButton13.setBackground(new java.awt.Color(41, 183, 212));
        jButton13.setText("Làm mới");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(41, 183, 212));
        jButton14.setText("Thêm khách hàng");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Yêu cầu đăng nhập từ quản lý");

        jLabel19.setText("Tài khoản");

        jLabel20.setText("Mật khẩu");

        jButton15.setBackground(new java.awt.Color(41, 183, 212));
        jButton15.setText("Làm mới");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb1.setText("Mã nhân viên");

        lb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb2.setText("Tên nhân viên");

        lb3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb3.setText("ID nhân viên");

        jLabel27.setText("Giảm giá");

        txtGiamGIa.setEditable(false);

        jLabel29.setText("Thành tiền");

        txtThanhTien.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Hóa đơn");

        jButton10.setBackground(new java.awt.Color(41, 183, 212));
        jButton10.setText("Đăng xuất");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(kkk)
                                .addGap(18, 18, 18)
                                .addComponent(jButton14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addGap(14, 14, 14)
                                .addComponent(jButton11)
                                .addGap(48, 164, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMHD_GH, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSP_GH, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuong_GH, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGuiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTK)
                                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(375, 375, 375))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton2)))
                                .addGap(121, 121, 121))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(458, 458, 458)
                                        .addComponent(jButton15)
                                        .addGap(90, 90, 90))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtGiamGIa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(101, 101, 101)
                                                .addComponent(txtTinhTong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane6)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtGG_GH, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(jButton4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMaKH_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(88, 88, 88)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton1)
                                                        .addGap(44, 44, 44)
                                                        .addComponent(jButton5))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rdo_tienMat)
                                                        .addGap(50, 50, 50)
                                                        .addComponent(rdo_quet)))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rdo_chuyen)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMaHD_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jButton6))
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lb2)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaKH_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lb3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rdo_tienMat)
                            .addComponent(rdo_quet)
                            .addComponent(rdo_chuyen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtGG_GH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kkk)
                            .addComponent(jButton14))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtMaHD_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6)
                                    .addComponent(jLabel21))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtMHD_GH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtSP_GH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtSoLuong_GH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton9)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtTinhTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtGiamGIa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtGuiLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12)
                            .addComponent(jButton13))))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkkActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm khách hàng", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (txtTimKH.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập số điện thoại");
                return;
            } else {
                String SDT = txtTimKH.getText();
                try {
                    service.timKiemKHHHH(SDT);
                    List<KhachHangModel> KH = service.timKiemKHHHH(SDT);
                    if (KH == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (KH.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng");
                        return; // kết thúc luôn

                    }
                    if (KH.size() == 1) {
                        txtMaKH_HD.setText(KH.get(0).getMaKH());
                        DefaultTableModel model = (DefaultTableModel) TblKH.getModel();
                       
                        model.setRowCount(0);
                        for (KhachHangModel khach : KH) {
                            Object[] row = new Object[]{
                                khach.getMaKH(), khach.getTenKH(), khach.getTk(), khach.getGioiTinh(), khach.getSdt()
                            };
                            model.addRow(row);

                        }
                        return;
                    }

                    DefaultTableModel model = (DefaultTableModel) TblKH.getModel();
                  
                    model.setRowCount(0);
                    for (KhachHangModel khach : KH) {
                        Object[] row = new Object[]{
                            khach.getMaKH(), khach.getTenKH(), khach.getNgaySinh(), khach.getGioiTinh(), khach.getSdt()
                        };
                        model.addRow(row);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }

            }
        }
    }//GEN-LAST:event_kkkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm sản phẩm", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (txtSP.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập mã sản phẩm");
                return;
            } else {
                String maSP = txtSP.getText();
                try {
                    service.timKiemSPPPPP(maSP);
                    List<SanPhamModel> SP = service.timKiemSPPPPP(maSP);
                    if (SP == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (SP.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
                        return; // kết thúc luôn

                    }

                    DefaultTableModel model = (DefaultTableModel) tblSP.getModel();

                    model.setRowCount(0);
                    for (SanPhamModel khach : SP) {
                        Object[] row = new Object[]{
                            khach.getMaSP(), khach.getTenSP(), khach.getSoLuong(), khach.getGiaBan()
                        };
                        model.addRow(row);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }
                txtSP_GH.setText("");

            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void TblKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblKHMouseClicked
        // TODO add your handling code here:
        int index = TblKH.getSelectedRow();
        if (index >= 0) {
            String maKH = TblKH.getValueAt(index, 0).toString();
            txtMaKH_HD.setText(maKH);
        }
    }//GEN-LAST:event_TblKHMouseClicked

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:
        int index = tblSP.getSelectedRow();
        if (index >= 0) {
            String maSP = tblSP.getValueAt(index, 0).toString();
            txtSP_GH.setText(maSP);
        }
    }//GEN-LAST:event_tblSPMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HoaDonMode HD = new HoaDonMode();
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm hóa đơn mới? ", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {

            if (txtMaKH_HD.getText().isBlank() || txtGG_GH.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin");

//           
            } else {
                HD.setMaNV(lb3.getText());

                HD.setmKH(txtMaKH_HD.getText());

                if (rdo_tienMat.isSelected()) {
                    HD.setThanhToan("1");
                }
                if (rdo_quet.isSelected()) {
                    HD.setThanhToan("2");
                }
                if (rdo_chuyen.isSelected()) {
                    HD.setThanhToan("3");
                }
                HD.setKhuyenMai(txtGG_GH.getText());

                try {
                    service.insert(HD);
                    JOptionPane.showMessageDialog(this, "Thêm thành công");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    return;
                }
                List<Hienthigannhat> HTGN = service.HienThiSPGN();

                //Kiểm tra danh sách
                if (HTGN == null) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    return; // kết thúc luôn
                }
                if (HTGN.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Rỗng");
                    return; // kết thúc luôn

                }
                //đổ dữ liệu vào bảng
                DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

                model.setRowCount(0);
                for (Hienthigannhat ht : HTGN) {
                    Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(), ht.getMaNV(),
                        ht.getGhiChu(), ht.TrangThaiHDGH()};
                    model.addRow(row);

                    

                }
txtMHD_GH.setText("");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm hóa đơn theo ID Khách Hàng", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (txtMaKH_HD.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập số ID Khách Hàng");
                return;
            } else {
                String maKH = txtMaKH_HD.getText();
                try {
                    service.hienthiHDtheomaKH(maKH);
                    List<Hienthigannhat> HTHDTKH = service.hienthiHDtheomaKH(maKH);
                    if (HTHDTKH == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (HTHDTKH.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn");
                        return; // kết thúc luôn

                    }

                    DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

                    model.setRowCount(0);
                    for (Hienthigannhat ht : HTHDTKH) {
                        Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(), ht.getMaNV(),
                            ht.getGhiChu(), ht.TrangThaiHDGH()};
                        model.addRow(row);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }
                txtMHD_GH.setText("");

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoadonMouseClicked
        // TODO add your handling code here:
        int index = tblHoadon.getSelectedRow();
        if (index >= 0) {
            String IDHD = tblHoadon.getValueAt(index, 0).toString();
            String trangThai = tblHoadon.getValueAt(index, 5).toString();
            txtMHD_GH.setText(IDHD);
            txtMaHD_HD.setText(IDHD);
            txtTrangThai.setText(trangThai);

        }
    }//GEN-LAST:event_tblHoadonMouseClicked

    private void tblSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSPMouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<Hienthigannhat> HTDS = service.HienThiHD(lb3.getText());

        //Kiểm tra danh sách
        if (HTDS == null) {
            JOptionPane.showMessageDialog(this, "Lỗi");
            return; // kết thúc luôn
        }
        if (HTDS.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rỗng");
            return; // kết thúc luôn

        }
        //đổ dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

        model.setRowCount(0);
        for (Hienthigannhat ht : HTDS) {
            Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(), ht.getMaNV(),
                            ht.getGhiChu(), ht.TrangThaiHDGH()};
            model.addRow(row);
            txtMHD_GH.setText("");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn hủy hóa đơn", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            int index = tblHoadon.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Chưa có đối tượng để hủy");
                return;
            }
            Hienthigannhat sp = service.HienThiHD(lb3.getText()).get(tblHoadon.getSelectedRow());
            int slsp = sp.getTrangThai();
            if (slsp == 3) {
                JOptionPane.showMessageDialog(this, "Hóa đơn đã hủy");
                return;
            }
            if (slsp == 2) {
                JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán nên không thể hủy");
                return;
            }

            String maHD = txtMaHD_HD.getText();

            List<GioHangModel> GH = service.listGioHang(maHD);
            if (!GH.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Phải xóa hết sản phẩm trong hóa đơn mới hủy được ");
                return;

            } else {
                if (txtMK.getText().isBlank() || txtTK.getText().isBlank()) {
                    JOptionPane.showMessageDialog(this, "Bạn phải được xác nhận từ quản lý");
                    return;
                }
                String taiKhoan = txtTK.getText();
                String MatKhau = txtMK.getText();
                List<GioHangModel> yc = service.yeuCau(taiKhoan, MatKhau);
                int chucVu = yc.get(0).getSoLuong();

                if (yc == null) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    return; // kết thúc luôn
                }
                if (yc.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu sai");
                    return; // kết thúc luôn
//
                }
                if (chucVu == 1) {
                    try {
                        service.delete(maHD);
                        JOptionPane.showMessageDialog(this, "Hủy thành công");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Hủy thất bại");
                    }
                    List<Hienthigannhat> HTDS = service.HienThiHD(lb3.getText());

                    //Kiểm tra danh sách
                    if (HTDS == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (HTDS.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Rỗng");
                        return; // kết thúc luôn

                    }
                    //đổ dữ liệu vào bảng
                    DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

                    model.setRowCount(0);
                    for (Hienthigannhat ht : HTDS) {
                        Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(), ht.getMaNV(),
                            ht.getGhiChu(), ht.TrangThaiHDGH()};
                        model.addRow(row);
                    }
                    txtMHD_GH.setText("");
                    txtTK.setText("");
                    txtMK.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn không phải là quản lý");
                    return;
                }

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn tìm kiếm hóa đơn theo ID Hóa Đơn", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            if (txtMaHD_HD.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập số ID Hóa Đơn");
                return;
            } else {
                String maHD = txtMaHD_HD.getText();
                try {
                    
                    List<Hienthigannhat> HTHDTHD = service.hienthiHDtheomaHD(maHD);
                    if (HTHDTHD == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (HTHDTHD.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn");
                        return; // kết thúc luôn

                    }

                    DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

                    model.setRowCount(0);
                    for (Hienthigannhat ht : HTHDTHD) {
                        Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(),
                            ht.TrangThaiHDGH()};
                        model.addRow(row);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }
                txtMHD_GH.setText("");

            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    public static boolean patternMatches(String emailAddress, String regexPattern) {
        return Pattern.compile(regexPattern)
                .matcher(emailAddress)
                .matches();
    }
    String regex = "\\D";
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        HoaDonChiTietModel HDCT = new HoaDonChiTietModel();

        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm vào giỏ hàng? ", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {

            if (txtMHD_GH.getText().isBlank() || txtSP_GH.getText().isBlank() || txtSoLuong_GH.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin");
                return;
            }
            String maSP = txtSP_GH.getText();
            SanPhamModel sp = service.timKiemSPPPPP(maSP).get(0);
            int slsp = sp.getSoLuong();
            if (slsp < Integer.parseInt(txtSoLuong_GH.getText())) {
                JOptionPane.showMessageDialog(this, "Sản phẩm không đủ");
                return;
            }
            if (Integer.parseInt(txtSoLuong_GH.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                return;
            }

            if (Integer.parseInt(txtSoLuong_GH.getText()) == 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                return;
            }

            if (patternMatches(txtSoLuong_GH.getText(), regex) == true) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên dương");
                return;

            }

            String maHD1 = txtMHD_GH.getText();
            Hienthigannhat sp1 = service.hienthiHDtheomaHD(maHD1).get(0);
            int trangthai = sp1.getTrangThai();
            if (trangthai == 2) {
                JOptionPane.showMessageDialog(this, "Thêm thất bại vì Hóa đơn đã thanh toán thành công");
                return;
            }
            if (trangthai == 3) {
                JOptionPane.showMessageDialog(this, "Thêm thất bại vì Hóa đơn đã hủy");
                return;
            } else {
                HDCT.setMaHD(txtMaHD_HD.getText());

                HDCT.setMaSp(txtSP_GH.getText());
                HDCT.setSoLuong(Integer.valueOf(txtSoLuong_GH.getText()));

                String maHD = txtMHD_GH.getText();
                String maSPp = txtSP_GH.getText();
                int soluongxoa = Integer.valueOf(txtSoLuong_GH.getText());

                try {
                    service.insertHDCT(HDCT);

                    JOptionPane.showMessageDialog(this, "Thêm thành công");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    return;
                }

                String maHDtim = txtMHD_GH.getText();
                try {
                    service.listGioHang(maHDtim);
                    List<GioHangModel> GH = service.listGioHang(maHDtim);
                    if (GH == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (GH.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy khách hanngf");
                        return; // kết thúc luôn

                    }

                    DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();

                    model.setRowCount(0);
                    for (GioHangModel khach : GH) {
                        Object[] row = new Object[]{
                            khach.getMaHDCT(), khach.getMaHD(),khach.getMaSP(), khach.getTenSp(), khach.getSoLuong(), khach.getTongTien()
                        };
                        model.addRow(row);

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }

                try {
                    service.suaSLSP(soluongxoa, maSP);
                    service.timKiemSPPPPP(maSP);
                    List<SanPhamModel> SP = service.timKiemSPPPPP(maSP);
                    if (SP == null) {
                        JOptionPane.showMessageDialog(this, "Lỗi");
                        return; // kết thúc luôn
                    }
                    if (SP.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Không tìm thấy khách hanngf");
                        return; // kết thúc luôn

                    }

                    DefaultTableModel model1 = (DefaultTableModel) tblSP.getModel();

                    model1.setRowCount(0);
                    for (SanPhamModel khach : SP) {
                        Object[] row = new Object[]{
                            khach.getMaSP(), khach.getTenSP(), khach.getSoLuong(), khach.getGiaBan()
                        };
                        model1.addRow(row);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
                }
                txtSP_GH.setText("");
                txtGG_GH.setText("");
                txtSoLuong_GH.setText("");

            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    private void loadTableGG() throws SQLException {
        List<giamGiamodel> GG = service.listGG();

        //Kiểm tra danh sách
        if (GG == null) {
            JOptionPane.showMessageDialog(this, "Lỗi");
            return; // kết thúc luôn
        }
        if (GG.isEmpty()) {
           txtGG_GH.setText("3");

        }
        txtGG_GH.setText(GG.get(0).getId());
        //đổ dữ liệu vào bảng
        DefaultTableModel model = (DefaultTableModel) tblGiamGia.getModel();

        model.setRowCount(0);
        for (giamGiamodel gg : GG) {
            Object[] row = new Object[]{gg.getId(), gg.getMagiamgia(), gg.getTenGiamGIa(), gg.getMucGG(), gg.getNgayBD(), gg.getNgayKT()};
            model.addRow(row);
        }
    }

    private void tblGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiamGiaMouseClicked
        // TODO add your handling code here:

        int index = tblGiamGia.getSelectedRow();
        if (index >= 0) {
            String maSP = tblGiamGia.getValueAt(index, 0).toString();
            txtGG_GH.setText(maSP);
        }
    }//GEN-LAST:event_tblGiamGiaMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dữ liệu", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {
            int index = tblGioHang.getSelectedRow();
            if (index == -1) {
                JOptionPane.showMessageDialog(this, "Chưa có đối tượng để xóa");
                return;
            }

            Hienthigannhat sp1 = service.hienthiHDtheomaHD(txtMHD_GH.getText()).get(0);
            int trangthai = sp1.getTrangThai();
            if (trangthai == 2) {
                JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán nên không xóa dược");
                return;
            }

            if (trangthai == 3) {
                JOptionPane.showMessageDialog(this, "Hoá đơn này đã hủy");
                return;
            }

            String maHDtim = txtMHD_GH.getText();

            GioHangModel sp = service.listGioHang(maHDtim).get(index);
            String maSP = sp.getMaSP();
            int slsp = sp.getSoLuong();
            String maHDCT = sp.getMaHDCT();
            try {
                service.deleteHDCT(maHDCT);
                service.themSLSP(slsp, maSP);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }

            try {
                service.listGioHang(maHDtim);
                List<GioHangModel> GH = service.listGioHang(maHDtim);
                if (GH == null) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    return; // kết thúc luôn
                }

                DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
                
                
                model.setRowCount(0);
                for (GioHangModel khach : GH) {
                    Object[] row = new Object[]{
                         khach.getMaHDCT(), khach.getMaHD(),khach.getMaSP(), khach.getTenSp(), khach.getSoLuong(), khach.getTongTien()
                    };
                    model.addRow(row);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
            }
            try {

                service.timKiemSPPPPP(maSP);
                List<SanPhamModel> SP = service.timKiemSPPPPP(maSP);
                if (SP == null) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    return; // kết thúc luôn
                }
                if (SP.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy khách hanngf");
                    return; // kết thúc luôn

                }

                DefaultTableModel model1 = (DefaultTableModel) tblSP.getModel();
                
                model1.setRowCount(0);
                for (SanPhamModel khach : SP) {
                    Object[] row = new Object[]{
                        khach.getMaSP(), khach.getTenSP(), khach.getSoLuong(), khach.getGiaBan()
                    };
                    model1.addRow(row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
            }
            txtSP_GH.setText("");
            txtGG_GH.setText("");
            txtSoLuong_GH.setText("");
            txtTK.setText("");
            txtMK.setText("");

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn hiển thị sản phẩm trong hóa đơn ", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {

            if (txtMHD_GH.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải ID hóa đơn trước");
                return;
            }
            String maHDtim = txtMHD_GH.getText();
            try {
                service.listGioHang(maHDtim);
                List<GioHangModel> GH = service.listGioHang(maHDtim);
                if (GH == null) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    return; // kết thúc luôn
                }
                if (GH.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Không có sản phẩm");
                    return; // kết thúc luôn

                }

                DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
                model.setRowCount(0);
                for (GioHangModel khach : GH) {
                    Object[] row = new Object[]{
                        khach.getMaHDCT(), khach.getMaHD(),khach.getMaSP(), khach.getTenSp(), khach.getSoLuong(), khach.getTongTien()
                    };
                    model.addRow(row);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hiển thị thất bại");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (txtMHD_GH.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn hóa đơn cần thanh toán trước");
            return;
        }
         List<Hienthigannhat> HTHDTHD = service.hienthiHDtheomaHD(txtMHD_GH.getText());
         txtGiamGIa.setText(HTHDTHD.get(0).getGhiChu());
        int index1 = tblHoadon.getSelectedRow();

        Hienthigannhat sp1 = service.HienThiHD(lb3.getText()).get(index1);
        int trangthai = sp1.getTrangThai();
        if (trangthai == 2) {
            JOptionPane.showMessageDialog(this, " Hóa đơn này đã thanh toán thành công");
            return;
        }
        if (trangthai == 3) {
            JOptionPane.showMessageDialog(this, " Hóa đơn này đã hủy");
            return;
        }

        String maHDtim = txtMHD_GH.getText();

        service.listGioHang(maHDtim);
        List<GioHangModel> GH = service.listGioHang(maHDtim);
        if (GH == null) {
            JOptionPane.showMessageDialog(this, "Lỗi");
            return; // kết thúc luôn
        }
        if (GH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có sản phẩm để tính");
            return; // kết thúc luôn

        }
        GioHangModel tien = service.tinhTong(maHDtim).get(0);
        txtTinhTong.setText(String.valueOf(tien.getTongTien()));
        txtThanhTien.setText(String.valueOf(tien.getTienGiam()));
        

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn thanh toán hóa đơn", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon == JOptionPane.YES_OPTION) {

            if (txtTinhTong.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Bạn phải tính tổng trước");
                return;
            }
//            if (txtSP_GH.getText().isBlank()) {
//                JOptionPane.showMessageDialog(this, "Bạn phải nhập mã Sản phẩm");
//                return;
//            }
            String maHD = txtMHD_GH.getText();

            Hienthigannhat sp1 = service.hienthiHDtheomaHD(maHD).get(0);
            int trangthai = sp1.getTrangThai();
            if (trangthai == 2) {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại vì Hóa đơn đã thanh toán thành công");
                return;
            }
            if (trangthai == 3) {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại vì Hóa đơn đã hủy");
                return;
            }

//            String slCS;
//            List<truSPModel> gg4 = service.listsoLuongspsua(maHD);
//            for (truSPModel gio : gg4) {
//             Object row[] = new Object[]{gio.getMaCTSP()};
//                for (Object ob : row) {
//                   
//                }
//            };
            String maSP = txtSP_GH.getText();
            double tien = Double.valueOf(txtThanhTien.getText());
            if (txtKhachDua.getText().isBlank()) {
                double khachDua = Double.valueOf(txtThanhTien.getText());

                txtGuiLai.setText(String.valueOf(khachDua - tien));

            } else {
                double khachDua = Double.valueOf(txtKhachDua.getText());

                txtGuiLai.setText(String.valueOf(khachDua - tien));
                ;
            }

            try {
                service.thanhtoanthanhcong(maHD, tien);
//                service.suaSLSP(maHD, maSP);
                JOptionPane.showMessageDialog(this, "Thanh toán thành công thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại thất bại");
            }
//           
             List<Hienthigannhat> HTHDTHD = service.hienthiHDtheomaHD(maHD);
                   

                    DefaultTableModel model = (DefaultTableModel) tblHoadon.getModel();

                    model.setRowCount(0);
                    for (Hienthigannhat ht : HTHDTHD) {
                        Object[] row = new Object[]{ht.getMaHD(), ht.getTenKH(), ht.getTenHTTT(), ht.getNgayTao(), ht.getGhiChu(),
                            ht.TrangThaiHDGH()};
                        model.addRow(row);
                    }
                
            txtGG_GH.setText("");
            txtMHD_GH.setText("");
            txtSP_GH.setText("");
            txtSoLuong_GH.setText("");

        }
    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachDuaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtKhachDuaActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        txtGG_GH.setText("");
        txtGuiLai.setText("");
        txtKhachDua.setText("");
        txtMHD_GH.setText("");
        txtMaHD_HD.setText("");
        txtMaKH_HD.setText("");

        txtSP.setText("");
        txtSP_GH.setText("");
        txtSoLuong_GH.setText("");
        txtTimKH.setText("");
        txtTinhTong.setText("");
        txtTrangThai.setText("");

        txtTK.setText("");
        txtMK.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        txtTK.setText("");
        txtMK.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int index = tblGioHang.getSelectedRow();
        if (index >= 0) {
            String idHD = tblGioHang.getValueAt(index, 1).toString();
            txtMHD_GH.setText(idHD);
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new dangNhapHD().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton kkk;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JRadioButton rdo_chuyen;
    private javax.swing.JRadioButton rdo_quet;
    private javax.swing.JRadioButton rdo_tienMat;
    private javax.swing.JTable tblGiamGia;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoadon;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField txtGG_GH;
    private javax.swing.JTextField txtGiamGIa;
    private javax.swing.JTextField txtGuiLai;
    private javax.swing.JTextField txtKhachDua;
    private javax.swing.JTextField txtMHD_GH;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtMaHD_HD;
    private javax.swing.JTextField txtMaKH_HD;
    private javax.swing.JTextField txtSP;
    private javax.swing.JTextField txtSP_GH;
    private javax.swing.JTextField txtSoLuong_GH;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKH;
    private javax.swing.JTextField txtTinhTong;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
